### ISSUE TITLE
Beta: Can't install on Windows

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#168] opened 2017-03-08 17:25 UTC
As @VsevolodTrofimov reports [here](https://github.com/felixrieseberg/ember-electron/issues/130#issuecomment-285091459)

> v 2.0 doesn't start on windows due to multiple platform specific (mac) dependencies.
> yarn declines to install it, installing with npm downloads multiple files that would not run.
> 
> ----
> 
> Used Windows 10 x64 bit, node v7.3.0
> 
> Yarn exits with "error macos-alias@0.2.11: The platform "win32" is incompatible with this module.
> error Found incompatible module"
> yarn declines to install it, installing with npm downloads multiple files that would not run.
> 
> ----
> 
> Package freezes when using electron-debug as production dependency

Yarn has a useful blame function included, which gives this output:
```sh
❯ yarn why macos-alias
yarn why v0.20.3
[1/4] 🤔  Why do we have the module "macos-alias"...?
[2/4] 🚚  Initialising dependency graph...
warning electron-prebuilt-compile > electron-compilers > jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning electron-prebuilt-compile > electron-compilers > jade > transformers@2.1.0: Deprecated, use jstransformer
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info This module exists because "electron-forge#electron-installer-dmg#appdmg#ds-store" depends on it.
info Disk size without dependencies: "396kB"
info Disk size with unique dependencies: "856kB"
info Disk size with transitive dependencies: "856kB"
info Amount of shared dependencies: 1
✨  Done in 3.47s.
```

Seems we should report this upstream in [electron-forge](https://github.com/electron-userland/electron-forge) if this is actually preventing installation. 

I don't have a Windows machine setup right now, but we should investigate.

**Comment by jacobq** [comment] 2017-03-08 17:29
Isn't this the same as the yarn optional dep issue --> https://github.com/electron-userland/electron-forge/issues/136 https://github.com/yarnpkg/yarn/issues/1435 ?

**Comment by VsevolodTrofimov** [comment] 2017-03-08 17:31
Currently trying to follow guide form @pichfl in #160, with pure NPM as this might be yarn specific issue and I didn't do manual linking previously

**Comment by jacobq** [comment] 2017-03-08 17:33
@VsevolodTrofimov I ran into this on my linux system and decided to just resolve by uninstalling `yarn` since there are so many changes up in the air at the moment, but obviously that's not really a solution.

**Comment by VsevolodTrofimov** [comment] 2017-03-08 17:36
@jacobq I don't know state of things for linux, npm and yarn do not intersect on windows, so I use npm for platfrom specific packages and yarn for everything else, uninstalling would change nothing for me, would report here as soon as I'm done with linking ember-electron,

**Comment by jacobq** [comment] 2017-03-08 17:47
I think the reason I had to uninstall is because even though I was not running it directly, it was getting automatically detected and used somewhere in the tooling and I didn't know how to prevent it from doing that.

Just did a quick test by creating an empty ember project via `ember new` and then trying to run `yarn add electron-forge`. It failed with an error like the one yarn `v0.21.3` but worked with the latest nightly build (`v0.23.0-20170308.0112`).

So I'm pretty sure this is a problem with `yarn` and a fix is already on its way to the release channel. You can either use a bleeding edge yarn build or don't use yarn at all.

**Comment by bendemboski** [comment] 2017-03-08 17:54
You have to use npm for now. This is caused by [this](https://github.com/yarnpkg/yarn/issues/1435) yarn bug. My fix for it has been merged into yarn/master, but not released yet.

**Comment by VsevolodTrofimov** [comment] 2017-03-08 18:05
Uninstalled yarn for now, as ember attempts to use it during `ember g ember-electron`

**Comment by VsevolodTrofimov** [comment] 2017-03-08 18:07
@pichfl please mention in your guide in #160 that ember wouldn't execute `ember g ember-electron` unless it is listed in `devDependencies` in `package.json`

**Comment by VsevolodTrofimov** [comment] 2017-03-08 18:14
Ok, after a while of manual linking \ dependecies editing it did install

**Comment by VsevolodTrofimov** [comment] 2017-03-08 18:19
result of `ember electron`
![default](https://cloud.githubusercontent.com/assets/10118898/23717368/97ed4388-0444-11e7-8744-a0d9bd3eb7e2.png)

---
running .exe form the ember-electron/out folder
![out](https://cloud.githubusercontent.com/assets/10118898/23717369/97ed781c-0444-11e7-855c-bd71523b6752.png)

Probably I should create separate issue for this.

---

Actually the very reason the whole thing with adding electron-debug as dependency took place

**Comment by VsevolodTrofimov** [comment] 2017-03-08 18:21
With 2.0.0-beta it (at least) doesn't leave `null` process in system.

**Comment by jacobq** [comment] 2017-03-08 18:22
@VsevolodTrofimov based on hitting this multiple times myself (and getting bailed out by @anulman :D) I suspect that the `.compilerc` file isn't getting copied into the package. There is some work in progress to prevent this from happening (see #123) but for now try adding it to the `copy-files` configuration for your project.

**Comment by VsevolodTrofimov** [comment] 2017-03-08 18:25
@jacobq same result with `.compilerc`

**Comment by anulman** [comment] 2017-03-09 23:12
@VsevolodTrofimov closing this issue as it turns out it was Yarn-based; can you create a new one about the packaged app not running?

To init that issue, also please set electron.js to open the dev tools window, and share output from that (e.g. does it not open the console at all, open the console and show error messages, etc? do events in your electron app lifecycle fire?)

**Closed by anulman** 2017-03-09 23:12 UTC

**Comment by VsevolodTrofimov** [comment] 2017-03-10 09:41
@anulman last screenshot should auto-open dev tools, using electron debug.
