### ISSUE TITLE
Error: cannot find module 'yauzl' when running 'ember install ember-electron'

### ISSUE THREAD

**Issue by bendebled** [felixrieseberg/ember-electron#114] opened 2016-12-24 23:54 UTC
I get a `cannot find module 'yauzl'` error when I try to install ember-electron.

Here is what I did on a brand new xubuntu 16.04.

```
sudo apt-get update
sudo apt-get upgrade

curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
sudo apt-get install nodejs

sudo npm install -g bower

sudo npm install -g ember-cli
sudo npm install -g phantomjs

sudo apt-get install g++
ember new testapp
cd testapp
ember install ember-electron
```

Here is the result of `ember install ember-electron` :
![ember-electron-issue](https://cloud.githubusercontent.com/assets/11504720/21469142/3862e324-ca3c-11e6-9de3-d1e2b5e527f1.PNG)

Am I doing something wrong or this is an issue?

ember-cli: 2.10.0
node: 6.9.2

Disclaimer: I'm very new to the electron, nodejs,... world.

**Comment by bendebled** [comment] 2016-12-26 13:37
After some research, it's only missing 5 packages. Therefore, you can install them manually with this command: `npm i -s yauzl asar sanitize-filename run-series get-package-info`

Hence, this is what I had to do to create a new ember-electron project:
```
ember new testapp
cd testapp
ember install ember-electron --> will complain about yauzl not being installed. You absolutely need to run this command before running the npm i -s command
npm i -s yauzl asar sanitize-filename run-series get-package-info
ember install ember-electron
```

Note: sudo installing npm packages as I did in my first post is not a good practice. See https://docs.npmjs.com/getting-started/fixing-npm-permissions for more informations.

This issue is now fixed, but I don't close it for now as I will probably not be the only one having this issue. Plus, this issue is probably due to an issue in the ember-electron project.

**Comment by 256dpi** [comment] 2017-01-17 20:29
Same here, I needed to install the following packages by hand to complete `ember install ember-electron`:

```
"dependencies": {
    "asar": "^0.13.0",
    "get-package-info": "^1.0.0",
    "home-path": "^1.0.3",
    "run-series": "^1.1.4",
    "sanitize-filename": "^1.6.1",
    "yauzl": "^2.7.0"
  },
```

**Comment by felixrieseberg** [comment] 2017-01-17 21:23
I'm on it! We didn't really change anything, so I'm wondering what happened in our dependencies that we're now in this situation 🤔

**Comment by felixrieseberg** [comment] 2017-01-17 21:24
Just to make things more weird, I cannot reproduce the issue (latest ember-cli). Would one of you be able to try to reproduce this again - maybe someone our in dependency chain already fixed it?

**Comment by 256dpi** [comment] 2017-01-17 21:32
To give a little more context, here are my steps to reproduce the problem on my machine:

My specs:

- Node: v6.9.1
- NPM: 3.10.8
- Ember-CLI: 2.10.0

The commands:

```
ember new ee-test
cd ee-test/
ember install ember-electron
```

The output:

```
Installed packages for tooling via npm.
installing ember-electron
? Overwrite config/environment.js? Yes, overwrite
  overwrite config/environment.js
  create electron.js
  create tests/electron.js
  create tests/package.json
  overwrite package.json
Ember Electron requires configuration. Please consult the Readme to ensure that this addon works!
https://github.com/felixrieseberg/ember-electron
  install packages electron, electron-packager, electron-rebuild, ember-inspector, devtron
module.js:471
    throw err;
    ^

Error: Cannot find module 'yauzl'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/256dpi/Development/Temp/ee-test/node_modules/extract-zip/index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
electron@1.4.14 postinstall: `node install.js`
Exit status 1
Error: electron@1.4.14 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (/Users/256dpi/Development/Temp/ee-test/node_modules/npm/lib/utils/lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/Users/256dpi/Development/Temp/ee-test/node_modules/npm/lib/utils/spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by bendebled** [comment] 2017-01-17 22:51
The way to reproduce the error has been given in my firsts posts for my situation.
I add that npm's version is 3.10.9

**Comment by li-xinyang** [comment] 2017-01-19 02:44
@256dpi after install those dependencies manually, I still have an `Exit status 1` (see detailed error message below)

```
Installed packages for tooling via npm.
installing ember-electron
? Overwrite config/environment.js? Yes, overwrite
  overwrite config/environment.js
  create electron.js
  create tests/electron.js
  create tests/package.json
  overwrite package.json
Ember Electron requires configuration. Please consult the Readme to ensure that this addon works!
https://github.com/felixrieseberg/ember-electron
  install packages electron, electron-packager, electron-rebuild, ember-inspector, devtron
module.js:457
    throw err;
    ^

Error: Cannot find module 'home-path'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/li-xinyang/Desktop/MSL_Training_2_Electron/node_modules/electron-download/build/index.js:11:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
electron@1.4.14 postinstall: `node install.js`
Exit status 1
Error: electron@1.4.14 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (/home/li-xinyang/Desktop/MSL_Training_2_Electron/node_modules/npm/lib/utils/lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/home/li-xinyang/Desktop/MSL_Training_2_Electron/node_modules/npm/lib/utils/spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by li-xinyang** [comment] 2017-01-19 02:56
I have the similar issue even after manually installed all the missing dependencies; however, I am able to install it successfully using commands below.

```
npm install ember-electron
ember g ember-electron
```

**Comment by davidchalifoux** [comment] 2017-01-21 03:14
I too can confirm that I am getting this error.

**Comment by anulman** [comment] 2017-02-23 00:06
Seems like this occurs when npm / deps were installed with sudo; also looks like two solutions have been offered (thx @bendebled & @li-xinyang).

@davidchalifoux did anything here help your issue?

Closing for now as I think this is "resolved", as far as ember-electron + the ember plugin ecosystem stand

**Closed by anulman** 2017-02-23 00:06 UTC

**Comment by wizpresso-steve-cy-fan** [comment] 2023-08-02 04:34
Instead of installing `spdlog` use this:
```
$ npm i -g @microsoft/1ds-core-js minimist yauzl yazl @vscode/spdlog xterm-headless
```
